load(":sleep.bzl", "sleep")


sleep(
  name = "sleep0",
  srcs = ["source.txt"]
)

sleep(
  name = "sleep1",
  srcs = ["source.txt"]
)

sleep(
  name = "sleep2",
  srcs = ["source.txt"]
)

sleep(
  name = "sleep3",
  srcs = ["source.txt"]
)

sleep(
  name = "sleep4",
  srcs = ["source.txt"]
)
